language: node_js
sudo: false
cache:
  directories:
    - $HOME/.npm
notifications:
  email:
    on_failure: always
node_js:
  - "8.10"
script:
  - npm run lint
  - npm test
  - npx codecov
deploy:
  skip_cleanup: true
  provider: script
  script: npx semantic-release
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
